### ISSUE TITLE
Dotrix Editor

### ISSUE THREAD

**Issue by Lowentwickler** [lowenware/dotrix#104]
The development goes side by side with changes in various engine parts.

## TODO

* [x] Add `editor` binary to the monorepo
* [x] Implement terrain rendering from a heightmap
* [ ] Implement heightmap edit brushes
* [ ] Implement LOD change based on camera distance
* [ ] Implement world project file format/import/export
